spring.application.name=demo

# Server
server.port=8080

#DB Properties
db.driverclass=oracle.jdbc.driver.OracleDriver
db.url=jdbc:oracle:thin:@//65.2.48.87:1521/xe
db.user=bbps
db.password=h95J3OG0zOEr8hyBE7x5oXcavrSTvgum5Iq7B9uuio7YCQv6+NMABnO2ZBi6QdNOg8FUEMqiRX4oTHvwlS7gKVtjwtp8W4G2O5hLEgeTcKWkosBVrrpKl6S+64E3BWqLBoPUl5XvNt4d


spring.datasource.url=jdbc:oracle:thin:@//65.2.48.87:1521/xe
spring.datasource.username=bbps
spring.datasource.password=bbps
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# JWT
jwt.secret=my-super-secret-key-my-super-secret-key-123456
# 15 minutes
jwt.access-token-expiration=900000
# 7 days
jwt.refresh-token-expiration=604800000







